---
  # General configuration
  epochs: 100
  batch_size: 32
  train_data: ./data/train
  val_data: null
  out_dir: exp/sample
  
  # Triplet loss + GOR configuration
  loss_margin: 1.0
  alpha_gor: 1.0
  
  # Model configuration
  weight: null
  freeze: all
  unfreeze: [fc, l2_norm]