---
  # General configuration
  epochs: 30
  batch_size: 32
  train_data: ./data/cropped224
  val_data: null
  out_dir: exp/run2/stage2
  
  # Triplet loss + GOR configuration
  loss_type: semihard
  loss_margin: 0.5
  alpha_gor: 1.0
  
  # Model configuration
  weight: exp/run2/stage1/final.pt
  model: MobileNetV3L_64
  freeze: all
  unfreeze: [fc, l2_norm, backbone.classifier, backbone.act2, backbone.conv_head, backbone.global_pool, "backbone.blocks[6]", "backbone.blocks[5]"]