---
  # General configuration
  epochs: 20
  batch_size: 32
  train_data: ./data/cropped224
  val_data: null
  out_dir: exp/run2/stage1
  
  # Triplet loss + GOR configuration
  loss_type: semihard
  loss_margin: 0.5
  alpha_gor: 1.0
  
  # Model configuration
  weight: null
  model: MobileNetV3L_64
  freeze: all
  unfreeze: [fc, l2_norm]