---
  # General configuration
  epochs: 10
  batch_size: 64
  train_data: ./data/cropped224
  val_data: null
  out_dir: exp/run3/stage1
  
  # Triplet loss + GOR configuration
  loss_type: hardest
  loss_margin: 0.2
  alpha_gor: 1.0
  
  # Model configuration
  weight: null
  model: MobileNetV3L_64
  freeze: all
  unfreeze: [fc, l2_norm]