---
  # General configuration
  epochs: 30
  batch_size: 64
  train_data: ./data/cropped224
  val_data: null
  out_dir: exp/run4/stage2
  
  # Triplet loss + GOR configuration
  loss_type: semihard
  loss_margin: 0.2
  alpha_gor: 1.0
  
  # Model configuration
  weight: exp/run4/stage1/final.pt
  model: EfficientNetV2B0_128
  freeze: all
  unfreeze: [fc, l2_norm, backbone.classifier, backbone.act2, backbone.conv_head, backbone.global_pool, backbone.bn2, "backbone.blocks[5]", "backbone.blocks[4]"]